package br.com.jcomputacao.cnab.Cef240;

/**
 * 03/09/2014 14:09:44
 *
 * @author Thiago
 */
public class LineCnabCaixaEconomicaRetornoSegmentoU {

    int CODIGO_BANCO_COMPENSACA;
    int LOTE_SERVIC;
    int TIPO_REGISTRO;
    int SEQUENCIAL_REGISTRO;
    String CODIGO_SEGMENTO_REGISTRO;
    String USO_EXCLUSIVO_FEBRABAN1;
    int CODIGO_MOVIMENTO_REMESS;
    int JUROS_MULTA_ENCARGO;
    int VALOR_DESCONTO_CONCEDIDO;
    int VALOR_ABATIMENTO_CONCEDIDO;
    int VALOR_IOF_RECOLHIDO;
    int VALOR_PAGO_SACADO;
    int VALOR_LIQUIDO_CREDITAR;
    int VALOR_OUTRAS_DESPESAS;
    int VALOR_OUTROS_CREDITOS;
    int DATA_OCORRENCI;
    int DATA_EFETIVACAO_CREDIT;
    int USO_EXCLUSIVO_FEBRABAN2;
    int DATA_DEBITO_TARIF;
    int CODIGO_SACADO_BANCO;
    int USO_EXCLUSIVO_FEBRABAN3;
    int CODIGO_BANCO_CORRESPONDENTE_COMPENSACA;
    int NOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO;
    String USO_EXCLUSIVO_FEBRABAN4;

    public int getCODIGO_BANCO_COMPENSACA() {
        return CODIGO_BANCO_COMPENSACA;
    }

    public void setCODIGO_BANCO_COMPENSACA(int CODIGO_BANCO_COMPENSACA) {
        this.CODIGO_BANCO_COMPENSACA = CODIGO_BANCO_COMPENSACA;
    }

    public int getLOTE_SERVIC() {
        return LOTE_SERVIC;
    }

    public void setLOTE_SERVIC(int LOTE_SERVIC) {
        this.LOTE_SERVIC = LOTE_SERVIC;
    }

    public int getTIPO_REGISTRO() {
        return TIPO_REGISTRO;
    }

    public void setTIPO_REGISTRO(int TIPO_REGISTRO) {
        this.TIPO_REGISTRO = TIPO_REGISTRO;
    }

    public int getSEQUENCIAL_REGISTRO() {
        return SEQUENCIAL_REGISTRO;
    }

    public void setSEQUENCIAL_REGISTRO(int SEQUENCIAL_REGISTRO) {
        this.SEQUENCIAL_REGISTRO = SEQUENCIAL_REGISTRO;
    }

    public String getCODIGO_SEGMENTO_REGISTRO() {
        return CODIGO_SEGMENTO_REGISTRO;
    }

    public void setCODIGO_SEGMENTO_REGISTRO(String CODIGO_SEGMENTO_REGISTRO) {
        this.CODIGO_SEGMENTO_REGISTRO = CODIGO_SEGMENTO_REGISTRO;
    }

    public String getUSO_EXCLUSIVO_FEBRABAN1() {
        return USO_EXCLUSIVO_FEBRABAN1;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN1(String USO_EXCLUSIVO_FEBRABAN1) {
        this.USO_EXCLUSIVO_FEBRABAN1 = USO_EXCLUSIVO_FEBRABAN1;
    }

    public int getCODIGO_MOVIMENTO_REMESS() {
        return CODIGO_MOVIMENTO_REMESS;
    }

    public void setCODIGO_MOVIMENTO_REMESS(int CODIGO_MOVIMENTO_REMESS) {
        this.CODIGO_MOVIMENTO_REMESS = CODIGO_MOVIMENTO_REMESS;
    }

    public int getJUROS_MULTA_ENCARGO() {
        return JUROS_MULTA_ENCARGO;
    }

    public void setJUROS_MULTA_ENCARGO(int JUROS_MULTA_ENCARGO) {
        this.JUROS_MULTA_ENCARGO = JUROS_MULTA_ENCARGO;
    }

    public int getVALOR_DESCONTO_CONCEDIDO() {
        return VALOR_DESCONTO_CONCEDIDO;
    }

    public void setVALOR_DESCONTO_CONCEDIDO(int VALOR_DESCONTO_CONCEDIDO) {
        this.VALOR_DESCONTO_CONCEDIDO = VALOR_DESCONTO_CONCEDIDO;
    }

    public int getVALOR_ABATIMENTO_CONCEDIDO() {
        return VALOR_ABATIMENTO_CONCEDIDO;
    }

    public void setVALOR_ABATIMENTO_CONCEDIDO(int VALOR_ABATIMENTO_CONCEDIDO) {
        this.VALOR_ABATIMENTO_CONCEDIDO = VALOR_ABATIMENTO_CONCEDIDO;
    }

    public int getVALOR_IOF_RECOLHIDO() {
        return VALOR_IOF_RECOLHIDO;
    }

    public void setVALOR_IOF_RECOLHIDO(int VALOR_IOF_RECOLHIDO) {
        this.VALOR_IOF_RECOLHIDO = VALOR_IOF_RECOLHIDO;
    }

    public int getVALOR_PAGO_SACADO() {
        return VALOR_PAGO_SACADO;
    }

    public void setVALOR_PAGO_SACADO(int VALOR_PAGO_SACADO) {
        this.VALOR_PAGO_SACADO = VALOR_PAGO_SACADO;
    }

    public int getVALOR_LIQUIDO_CREDITAR() {
        return VALOR_LIQUIDO_CREDITAR;
    }

    public void setVALOR_LIQUIDO_CREDITAR(int VALOR_LIQUIDO_CREDITAR) {
        this.VALOR_LIQUIDO_CREDITAR = VALOR_LIQUIDO_CREDITAR;
    }

    public int getVALOR_OUTRAS_DESPESAS() {
        return VALOR_OUTRAS_DESPESAS;
    }

    public void setVALOR_OUTRAS_DESPESAS(int VALOR_OUTRAS_DESPESAS) {
        this.VALOR_OUTRAS_DESPESAS = VALOR_OUTRAS_DESPESAS;
    }

    public int getVALOR_OUTROS_CREDITOS() {
        return VALOR_OUTROS_CREDITOS;
    }

    public void setVALOR_OUTROS_CREDITOS(int VALOR_OUTROS_CREDITOS) {
        this.VALOR_OUTROS_CREDITOS = VALOR_OUTROS_CREDITOS;
    }

    public int getDATA_OCORRENCI() {
        return DATA_OCORRENCI;
    }

    public void setDATA_OCORRENCI(int DATA_OCORRENCI) {
        this.DATA_OCORRENCI = DATA_OCORRENCI;
    }

    public int getDATA_EFETIVACAO_CREDIT() {
        return DATA_EFETIVACAO_CREDIT;
    }

    public void setDATA_EFETIVACAO_CREDIT(int DATA_EFETIVACAO_CREDIT) {
        this.DATA_EFETIVACAO_CREDIT = DATA_EFETIVACAO_CREDIT;
    }

    public int getUSO_EXCLUSIVO_FEBRABAN2() {
        return USO_EXCLUSIVO_FEBRABAN2;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN2(int USO_EXCLUSIVO_FEBRABAN2) {
        this.USO_EXCLUSIVO_FEBRABAN2 = USO_EXCLUSIVO_FEBRABAN2;
    }

    public int getDATA_DEBITO_TARIF() {
        return DATA_DEBITO_TARIF;
    }

    public void setDATA_DEBITO_TARIF(int DATA_DEBITO_TARIF) {
        this.DATA_DEBITO_TARIF = DATA_DEBITO_TARIF;
    }

    public int getCODIGO_SACADO_BANCO() {
        return CODIGO_SACADO_BANCO;
    }

    public void setCODIGO_SACADO_BANCO(int CODIGO_SACADO_BANCO) {
        this.CODIGO_SACADO_BANCO = CODIGO_SACADO_BANCO;
    }

    public int getUSO_EXCLUSIVO_FEBRABAN3() {
        return USO_EXCLUSIVO_FEBRABAN3;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN3(int USO_EXCLUSIVO_FEBRABAN3) {
        this.USO_EXCLUSIVO_FEBRABAN3 = USO_EXCLUSIVO_FEBRABAN3;
    }

    public int getCODIGO_BANCO_CORRESPONDENTE_COMPENSACA() {
        return CODIGO_BANCO_CORRESPONDENTE_COMPENSACA;
    }

    public void setCODIGO_BANCO_CORRESPONDENTE_COMPENSACA(int CODIGO_BANCO_CORRESPONDENTE_COMPENSACA) {
        this.CODIGO_BANCO_CORRESPONDENTE_COMPENSACA = CODIGO_BANCO_CORRESPONDENTE_COMPENSACA;
    }

    public int getNOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO() {
        return NOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO;
    }

    public void setNOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO(int NOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO) {
        this.NOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO = NOSSO_NUMERO_BANCO_CORRESPONDENTE_COMPENSACAO;
    }

    public String getUSO_EXCLUSIVO_FEBRABAN4() {
        return USO_EXCLUSIVO_FEBRABAN4;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN4(String USO_EXCLUSIVO_FEBRABAN4) {
        this.USO_EXCLUSIVO_FEBRABAN4 = USO_EXCLUSIVO_FEBRABAN4;
    }    
    
}
