package br.com.jcomputacao.cnab.Cef240;

/**
 * 04/09/2014 13:03:00
 *
 * @author Thiago
 */
public class LineCnabCaixaEconomicaRetornoTrailerLote {

    int CODIGO_BANCO_COMPENSACAO;
    int LOTE_SERVICO;
    int TIPO_REGISTRO;
    String USO_EXCLUSIVO_FEBRABAN1;
    int QUANTIDADE_REGISTROS_LOTE;
    int QUANTIDADE_TITULOS_COBRANCA;
    int VALOR_TITULOS_CARTEIRA;
    int QUANTIDADE_TITULOS_COBRANCA_CAUCIONADA;
    int VALOR_TITULOS_CARTEIRA_CAUCIONADA;
    int QUANTIDADE_TITULOS_COBRANCA_DESCONTADA;
    int QUANTIDADE_TITULOS_CARTEIRA_DESCONTADA;
    String USO_EXCLUSIVO_FEBRABAN2;
    String USO_EXCLUSIVO_FEBRABAN3;

    public int getCODIGO_BANCO_COMPENSACAO() {
        return CODIGO_BANCO_COMPENSACAO;
    }

    public void setCODIGO_BANCO_COMPENSACAO(int CODIGO_BANCO_COMPENSACAO) {
        this.CODIGO_BANCO_COMPENSACAO = CODIGO_BANCO_COMPENSACAO;
    }

    public int getLOTE_SERVICO() {
        return LOTE_SERVICO;
    }

    public void setLOTE_SERVICO(int LOTE_SERVICO) {
        this.LOTE_SERVICO = LOTE_SERVICO;
    }

    public int getTIPO_REGISTRO() {
        return TIPO_REGISTRO;
    }

    public void setTIPO_REGISTRO(int TIPO_REGISTRO) {
        this.TIPO_REGISTRO = TIPO_REGISTRO;
    }

    public String getUSO_EXCLUSIVO_FEBRABAN1() {
        return USO_EXCLUSIVO_FEBRABAN1;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN1(String USO_EXCLUSIVO_FEBRABAN1) {
        this.USO_EXCLUSIVO_FEBRABAN1 = USO_EXCLUSIVO_FEBRABAN1;
    }

    public int getQUANTIDADE_REGISTROS_LOTE() {
        return QUANTIDADE_REGISTROS_LOTE;
    }

    public void setQUANTIDADE_REGISTROS_LOTE(int QUANTIDADE_REGISTROS_LOTE) {
        this.QUANTIDADE_REGISTROS_LOTE = QUANTIDADE_REGISTROS_LOTE;
    }

    public int getQUANTIDADE_TITULOS_COBRANCA() {
        return QUANTIDADE_TITULOS_COBRANCA;
    }

    public void setQUANTIDADE_TITULOS_COBRANCA(int QUANTIDADE_TITULOS_COBRANCA) {
        this.QUANTIDADE_TITULOS_COBRANCA = QUANTIDADE_TITULOS_COBRANCA;
    }

    public int getVALOR_TITULOS_CARTEIRA() {
        return VALOR_TITULOS_CARTEIRA;
    }

    public void setVALOR_TITULOS_CARTEIRA(int VALOR_TITULOS_CARTEIRA) {
        this.VALOR_TITULOS_CARTEIRA = VALOR_TITULOS_CARTEIRA;
    }

    public int getQUANTIDADE_TITULOS_COBRANCA_CAUCIONADA() {
        return QUANTIDADE_TITULOS_COBRANCA_CAUCIONADA;
    }

    public void setQUANTIDADE_TITULOS_COBRANCA_CAUCIONADA(int QUANTIDADE_TITULOS_COBRANCA_CAUCIONADA) {
        this.QUANTIDADE_TITULOS_COBRANCA_CAUCIONADA = QUANTIDADE_TITULOS_COBRANCA_CAUCIONADA;
    }

    public int getVALOR_TITULOS_CARTEIRA_CAUCIONADA() {
        return VALOR_TITULOS_CARTEIRA_CAUCIONADA;
    }

    public void setVALOR_TITULOS_CARTEIRA_CAUCIONADA(int VALOR_TITULOS_CARTEIRA_CAUCIONADA) {
        this.VALOR_TITULOS_CARTEIRA_CAUCIONADA = VALOR_TITULOS_CARTEIRA_CAUCIONADA;
    }

    public int getQUANTIDADE_TITULOS_COBRANCA_DESCONTADA() {
        return QUANTIDADE_TITULOS_COBRANCA_DESCONTADA;
    }

    public void setQUANTIDADE_TITULOS_COBRANCA_DESCONTADA(int QUANTIDADE_TITULOS_COBRANCA_DESCONTADA) {
        this.QUANTIDADE_TITULOS_COBRANCA_DESCONTADA = QUANTIDADE_TITULOS_COBRANCA_DESCONTADA;
    }

    public int getQUANTIDADE_TITULOS_CARTEIRA_DESCONTADA() {
        return QUANTIDADE_TITULOS_CARTEIRA_DESCONTADA;
    }

    public void setQUANTIDADE_TITULOS_CARTEIRA_DESCONTADA(int QUANTIDADE_TITULOS_CARTEIRA_DESCONTADA) {
        this.QUANTIDADE_TITULOS_CARTEIRA_DESCONTADA = QUANTIDADE_TITULOS_CARTEIRA_DESCONTADA;
    }

    public String getUSO_EXCLUSIVO_FEBRABAN2() {
        return USO_EXCLUSIVO_FEBRABAN2;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN2(String USO_EXCLUSIVO_FEBRABAN2) {
        this.USO_EXCLUSIVO_FEBRABAN2 = USO_EXCLUSIVO_FEBRABAN2;
    }

    public String getUSO_EXCLUSIVO_FEBRABAN3() {
        return USO_EXCLUSIVO_FEBRABAN3;
    }

    public void setUSO_EXCLUSIVO_FEBRABAN3(String USO_EXCLUSIVO_FEBRABAN3) {
        this.USO_EXCLUSIVO_FEBRABAN3 = USO_EXCLUSIVO_FEBRABAN3;
    }
    
    
}
